name: Testing code and deploy to DockerHub
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on: push
jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11", "3.12" ]

    services:
      mongo:
        image: mongo:7
        ports:
          - 27017:27017

    steps:
      - name: Setup Python
        uses: actions/setup-python@4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          pipx --version
          pipx install poetry
          poetry --version

      - name: Get repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: poetry install --with test

      - name: Testing with pytest
        run: poetry run pytest

# TODO: добавить сборку проекта в контейнер и тестирование контейнера
